// LOCALHOST 
GET http://localhost:3000/api-docs HTTP/1.1

### GET all artwork
GET http://localhost:3000/artwork/ HTTP/1.1

### GET artwork by id
GET http://localhost:3000/artwork/644f6ca79823b4c1e6920401 HTTP/1.1

### CREATE artwork
POST http://localhost:3000/artwork HTTP/1.1 
content-type: application/json
{
"artTitle": "Head of a Woman", "artYear": "1508", "artPeriod": "xxxx xxxxxxxxxxx", "artDesc": "also known as La Scapigliata", "artType": "Oil paint", "artLocation": "Galleria Nazionale di Parma", "artDonated": "", "artFile": "headwoman.jpg"
}

### CHANGE artwork by id
PUT http://localhost:3000/artwork/63f1af8bc8ad51af18312fd0 HTTP/1.1 
content-type: application/json
{
"artPeriod": "High Renaissance"
}

### DELETE artwork by id
DELETE http://localhost:3000/artwork/63e859e9bd16449396cca6ad HTTP/1.1

### Repeat for contact collection.

### GET all contacts
GET http://localhost:3000/contact/ HTTP/1.1

### GET contact by id
GET http://localhost:3000/contact/647590edd000510a473629b3 HTTP/1.1


// PRODUCTION Deploy

GET http://victor-341w05.onrender.com/api-docs HTTP/1.1

### GET all artwork
GET https://victor-341w05.onrender.com/artwork

### GET artwork by id
GET https://victor-341w05.onrender.com/artwork/644f6c8d9823b4c1e691b60a

### CREATE artwork
POST https://victor-341w05.onrender.com/artwork HTTP/1.1 
content-type: application/json
{
"artTitle": "Head of a Woman", "artYear": "1508", "artPeriod": "xxxx xxxxxxxxxxx", "artDesc": "also known as La Scapigliata", "artType": "Oil paint", "artLocation": "Galleria Nazionale di Parma", "artDonated": "", "artFile": "headwoman.jpg"
}

### CHANGE artwork by id
PUT https://victor-341w05.onrender.com/artwork/63f1af8bc8ad51af18312fd0 HTTP/1.1 
content-type: application/json
{
"artPeriod": "High Renaissance"
}

### DELETE artwork by id
DELETE https://victor-341w05.onrender.com/artwork/63e859e9bd16449396cca6ad HTTP/1.1

### Repeat for contact collection.

### GET all contacts
GET https://victor-341w05.onrender.com/contacts

### GET contact by id
GET https://victor-341w05.onrender.com/contacts/646a8ac28b9fb2279db1b82f

### CHANGE contact
PUT https://victor-341w05.onrender.com/artwork/64605f0f470f6bc234fd04cd HTTP/1.1
content-type: application/json
{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"sarahB@gmail.com",
    "phone":"1234567890",
    "role":"Art Restorer"
}

### DELETE contact
DELETE https://victor-341w05.onrender.com/contacts/64605f0f470f6bc234fd04cd HTTP/1.1

